package main

// Command detect scans this machine's hardware (CPU / RAM / GPU / displays /
// audio) and prints a capabilities.yaml draft (design P2-32) — the plan's
// "hardware scan → card draft" path, so a new node goes from `panda detect`
// to a reviewable card in one step. Detection is best-effort: anything that
// cannot be probed is emitted as an unknown value for the user to fill in.
//
//	panda detect                # print draft to stdout
//	panda detect -o capabilities.yaml

import (
	"context"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"regexp"
	"runtime"
	"strconv"
	"strings"
	"time"

	"github.com/Xustalis/OpenPanda/internal/agents"
	"github.com/Xustalis/OpenPanda/internal/ledger"
	versionpkg "github.com/Xustalis/OpenPanda/internal/version"
	"gopkg.in/yaml.v3"
)

func runDetect(args []string) {
	fs := flag.NewFlagSet("detect", flag.ExitOnError)
	out := fs.String("o", "", "write the draft to this file instead of stdout")
	fs.Parse(args)

	card := detectCard()
	data, err := yaml.Marshal(card)
	if err != nil {
		fatal("render capabilities draft", err)
	}
	header := fmt.Sprintf("# capabilities.yaml draft — generated by `panda detect` %s on %s\n"+
		"# Review the unknown/placeholder values, then start the daemon with --card <this file>.\n\n",
		versionpkg.Version, time.Now().Format("2006-01-02 15:04"))

	if *out != "" {
		if err := os.WriteFile(*out, append([]byte(header), data...), 0o644); err != nil {
			fatal("write draft", err)
		}
		fmt.Printf("capabilities draft written to %s — review it before use\n", *out)
		return
	}
	fmt.Print(header)
	fmt.Print(string(data))
}

// detectCard probes the host and assembles a Card draft.
func detectCard() ledger.Card {
	cores := runtime.NumCPU()
	ramGB := detectRAMGB()
	gpus := detectGPUs()
	displays := detectDisplays()
	audio := detectAudio()

	// Resource class from RAM: <8GB = Micro, <32GB = Standard, else Full.
	class := "Standard"
	switch {
	case ramGB > 0 && ramGB < 8:
		class = "Micro"
	case ramGB >= 32:
		class = "Full"
	}
	maxConcurrent := 2
	if cores >= 8 {
		maxConcurrent = 4
	}

	card := ledger.Card{
		Device:        hostname(),
		ResourceClass: class,
		Chip:          detectCPUModel(),
		Capacity: ledger.Capacity{
			CPUCores:      cores,
			RAMGB:         ramGB,
			MaxConcurrent: maxConcurrent,
		},
		ResourceProfile: ledger.ResourceProfile{
			CPU:          cores,
			RAMGB:        ramGB,
			GPUVRAMGB:    detectGPUVRAMGB(gpus),
			DurationHint: "short",
		},
	}

	// Agents: probe every known agent CLI from the registry (internal/agents)
	// and prewire the ones present. The registry is the single source of truth
	// shared with `panda agents`, the web settings API, and the commander's
	// availability probe, so the draft stays in lock-step with them.
	card.Agents = cardAgents()

	_ = displays
	_ = audio
	return card
}

// cardAgents scans the agent registry and returns a card.Agents map with one
// entry per installed CLI. Adapter names come from the registry (not the key),
// so a generated draft resolves to the real adapters/*.py script.
func cardAgents() map[string]ledger.Agent {
	out := map[string]ledger.Agent{}
	for _, k := range agents.Registry() {
		bin := k.PrimaryBinary()
		if bin == "" {
			continue
		}
		if _, err := exec.LookPath(bin); err != nil {
			continue
		}
		out[k.Name] = ledger.Agent{
			Adapter:      k.Adapter,
			InstallCheck: "which " + bin,
			Capabilities: []string{"coding", "shell", "file_edit"},
			BestAt:       []string{"multi_file_edits", "code_search", "running_tests"},
			NotFor:       []string{"hardware_io", "realtime_control"},
			CostTier:     "high",
			Tier:         2,
		}
	}
	return out
}

func hostname() string {
	h, err := os.Hostname()
	if err != nil || h == "" {
		return "unknown-host"
	}
	return h
}

// probe runs a command with a short timeout and returns trimmed stdout.
func probe(name string, args ...string) string {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	out, err := exec.CommandContext(ctx, name, args...).Output()
	if err != nil {
		return ""
	}
	return strings.TrimSpace(string(out))
}

func detectCPUModel() string {
	switch runtime.GOOS {
	case "darwin":
		return probe("sysctl", "-n", "machdep.cpu.brand_string")
	case "linux":
		if out := probe("sh", "-c", "grep -m1 'model name' /proc/cpuinfo"); out != "" {
			if _, v, ok := strings.Cut(out, ":"); ok {
				return strings.TrimSpace(v)
			}
		}
		if out := probe("lscpu"); out != "" {
			for _, line := range strings.Split(out, "\n") {
				if strings.HasPrefix(line, "Model name:") {
					return strings.TrimSpace(strings.TrimPrefix(line, "Model name:"))
				}
			}
		}
	}
	return fmt.Sprintf("%s/%s (unknown model)", runtime.GOOS, runtime.GOARCH)
}

func detectRAMGB() int {
	switch runtime.GOOS {
	case "darwin":
		if out := probe("sysctl", "-n", "hw.memsize"); out != "" {
			if n, err := strconv.ParseInt(out, 10, 64); err == nil {
				return int(n / (1 << 30))
			}
		}
	case "linux":
		if out := probe("sh", "-c", "grep -m1 MemTotal /proc/meminfo"); out != "" {
			re := regexp.MustCompile(`(\d+)\s*kB`)
			if m := re.FindStringSubmatch(out); m != nil {
				if n, err := strconv.Atoi(m[1]); err == nil {
					return n / (1024 * 1024)
				}
			}
		}
	}
	return 0
}

// detectGPUs lists GPU names (best effort). macOS uses system_profiler; on
// Linux lspci is attempted and falls back to none.
func detectGPUs() []string {
	switch runtime.GOOS {
	case "darwin":
		out := probe("system_profiler", "SPDisplaysDataType")
		if out == "" {
			return nil
		}
		var gpus []string
		for _, line := range strings.Split(out, "\n") {
			if strings.Contains(line, "Chipset Model:") {
				if _, v, ok := strings.Cut(strings.TrimSpace(line), "Chipset Model:"); ok {
					gpus = append(gpus, strings.TrimSpace(v))
				}
			}
		}
		return gpus
	case "linux":
		out := probe("sh", "-c", "lspci 2>/dev/null | grep -i 'vga\\|3d controller' || true")
		if out == "" {
			return nil
		}
		var gpus []string
		for _, line := range strings.Split(out, "\n") {
			if _, v, ok := strings.Cut(line, ": "); ok {
				gpus = append(gpus, strings.TrimSpace(v))
			}
		}
		return gpus
	}
	return nil
}

// detectGPUVRAMGB reads VRAM from system_profiler on macOS; unknown (0) elsewhere.
func detectGPUVRAMGB(gpus []string) int {
	if len(gpus) == 0 || runtime.GOOS != "darwin" {
		return 0
	}
	out := probe("system_profiler", "SPDisplaysDataType")
	for _, line := range strings.Split(out, "\n") {
		if strings.Contains(line, "VRAM") {
			// e.g. "VRAM (Total): 8 GB" / "VRAM (Shared): 16 GB"
			re := regexp.MustCompile(`(\d+)\s*GB`)
			if m := re.FindStringSubmatch(line); m != nil {
				if n, err := strconv.Atoi(m[1]); err == nil {
					return n
				}
			}
		}
	}
	return 0
}

// detectDisplays reports the display count (best effort, macOS only).
func detectDisplays() int {
	if runtime.GOOS != "darwin" {
		return 0
	}
	out := probe("system_profiler", "SPDisplaysDataType")
	return strings.Count(out, "Resolution:")
}

// detectAudio reports whether an audio input device exists (best effort, macOS only).
func detectAudio() bool {
	if runtime.GOOS != "darwin" {
		return false
	}
	out := probe("system_profiler", "SPAudioDataType")
	return strings.Contains(out, "Input Source") || strings.Contains(out, "Microphone")
}
