package main

// Command detect scans this machine's hardware (CPU / RAM / GPU / displays /
// audio) and prints a capabilities.yaml draft (design P2-32) — the plan's
// "hardware scan → card draft" path, so a new node goes from `panda detect`
// to a reviewable card in one step. Detection is best-effort: anything that
// cannot be probed is emitted as an unknown value for the user to fill in.
//
//	panda detect                # print draft to stdout
//	panda detect -o capabilities.yaml
//
// The probing itself lives in internal/carddetect (hardware details in
// internal/hwinfo), shared with `panda card rescan`, `panda card edit`'s
// draft and the panel's /api/self, so the numbers a node advertises cannot
// depend on which surface produced them.

import (
	"flag"
	"fmt"
	"os"
	"time"

	"github.com/Xustalis/OpenPanda/internal/carddetect"
	"github.com/Xustalis/OpenPanda/internal/ledger"
	versionpkg "github.com/Xustalis/OpenPanda/internal/version"
	"gopkg.in/yaml.v3"
)

func runDetect(args []string) {
	fs := flag.NewFlagSet("detect", flag.ExitOnError)
	out := fs.String("o", "", "write the draft to this file instead of stdout")
	fs.Parse(args)

	card := detectCard()
	data, err := yaml.Marshal(card)
	if err != nil {
		fatal("render capabilities draft", err)
	}
	header := fmt.Sprintf("# capabilities.yaml draft — generated by `panda detect` %s on %s\n"+
		"# Review the unknown/placeholder values, then start the daemon with --card <this file>.\n\n",
		versionpkg.Display(), time.Now().Format("2006-01-02 15:04"))

	if *out != "" {
		if err := os.WriteFile(*out, append([]byte(header), data...), 0o644); err != nil {
			fatal("write draft", err)
		}
		fmt.Printf("capabilities draft written to %s — review it before use\n", *out)
		return
	}
	fmt.Print(header)
	fmt.Print(string(data))
}

// detectCard probes the host and assembles a Card draft.
func detectCard() ledger.Card {
	return carddetect.DetectCard()
}
